name: Update Lunch Pages

on:
  schedule:
    - cron: '0 6 * * 1-5'  # Every weekday at 06:00 UTC, 8 AM Sweden
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: ["gh-pages"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Scrape and generate pages
      run: python main.py --all --refresh

    - name: Configure Git for GitHub Actions
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/*.html data/lunch_data_*.json
        git commit -m "Automated lunch update" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
