name: Update Lunch Data and Deploy

# This workflow now runs entirely from the main branch
# GitHub Pages should be configured to deploy from main branch /docs folder
on:
  schedule:
    # Run every day at 6:00 AM UTC (8:00 AM CEST)
    - cron: '0 6 * * 1-5'  # Monday to Friday only
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  scrape-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3)
        echo "Chrome version: $CHROME_VERSION"
        
        # Get compatible ChromeDriver version using the new Chrome for Testing API
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION%.*.*}")
        
        # If that fails, try getting the latest stable version
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE")
        fi
        
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # Download and install ChromeDriver
        wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip"
        sudo unzip /tmp/chromedriver.zip -d /tmp/
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
        # Verify installation
        chromedriver --version
        
    - name: Get current day
      id: get-day
      run: |
        DAY=$(python -c "from utils.utils import get_today_english; print(get_today_english().lower())")
        echo "day=$DAY" >> $GITHUB_OUTPUT
        echo "Current day: $DAY"
        
    - name: Scrape lunch data for current day
      run: |
        echo "Scraping data for: ${{ steps.get-day.outputs.day }}"
        python main.py --day ${{ steps.get-day.outputs.day }} --refresh
        
    - name: Generate fresh HTML page
      run: |
        echo "Generating fresh HTML page for the current day"
        python generate_html.py
        
    - name: Copy files to deployment directory
      run: |
        # Ensure CNAME is in docs directory for custom domain
        if [ -f CNAME ]; then
          cp CNAME docs/
        fi
        
        # The generate_html.py script already creates both index.html and docs/index.html
        # No need to copy manually as it's already done by the script
        echo "HTML files already generated by generate_html.py script"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Pull latest changes to avoid conflicts
        git pull origin main --no-edit || echo "Pull failed, continuing..."
        
        git add data/ docs/ index.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: ${{ steps.get-day.outputs.day }} lunch data $(date +'%Y-%m-%d %H:%M')"
          
          # Try to push, with retry logic
          for i in {1..3}; do
            if git push origin main; then
              echo "Push successful on attempt $i"
              break
            else
              echo "Push failed on attempt $i, trying to pull and retry..."
              git pull origin main --no-edit --strategy-option=ours || echo "Pull failed"
              if [ $i -eq 3 ]; then
                echo "All push attempts failed"
                exit 1
              fi
            fi
          done
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scrape-and-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 